// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';


var $$Event = /* module */[];

var Classlist = /* module */[];

var $$Node = /* module */[/* Classlist */Classlist];

exports.$$Event = $$Event;
exports.$$Node = $$Node;
/* No side effect */
