// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var $$Array = require("bs-platform/lib/js/array.js");
var Decco = require("@ryb73/decco/src/Decco.js");
var $$String = require("bs-platform/lib/js/string.js");
var Belt_Array = require("bs-platform/lib/js/belt_Array.js");

var resource_encode = Decco.stringToJson;

var resource_decode = Decco.stringFromJson;

function apiResource_encode(v) {
  return Decco.arrayToJson(resource_encode, v);
}

function apiResource_decode(v) {
  return Decco.arrayFromJson(resource_decode, v);
}

function faviconUrl(url) {
  return "https://" + (List.hd($$Array.to_list(url.replace("http://", "").replace("https://", "").split("/"))) + "/favicon.ico");
}

function getSiteName(url) {
  var chunk = url.replace("http://", "").replace("https://", "").split(".");
  return $$String.capitalize(Belt_Array.getExn(chunk, 0));
}

exports.resource_encode = resource_encode;
exports.resource_decode = resource_decode;
exports.apiResource_encode = apiResource_encode;
exports.apiResource_decode = apiResource_decode;
exports.faviconUrl = faviconUrl;
exports.getSiteName = getSiteName;
/* No side effect */
