// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';


var hourRef = /* record */[/* contents */0];

var minutesRef = /* record */[/* contents */0];

function init(param) {
  var hourElement = document.querySelector(".js-hour");
  var setHour = function (param) {
    var today = new Date(Date.now());
    var hour = today.getHours();
    var minutes = today.getMinutes();
    if (hour !== hourRef[0] || minutes !== minutesRef[0]) {
      hourRef[0] = hour;
      minutesRef[0] = minutes;
      hourElement.innerHTML = "" + (String(hour) + ("<span>:</span>" + (String(minutes) + "")));
      return /* () */0;
    } else {
      return /* () */0;
    }
  };
  setHour(/* () */0);
  setInterval((function (param) {
          setHour(/* () */0);
          return /* () */0;
        }), 1000);
  return /* () */0;
}

function init$1(param) {
  var addButtonElement = document.querySelector(".js-quick-links-add");
  var modalElement = document.querySelector(".js-quick-links-modal");
  var modalOverlayElement = document.querySelector(".js-quick-links-modal-overlay");
  var formElement = document.querySelector(".js-quick-links-form");
  var inputElement = document.querySelector(".js-quick-links-form-input");
  var toggleModal = function (param) {
    modalElement.classList.toggle("quick-links-modal--visible");
    return /* () */0;
  };
  addButtonElement.addEventListener("click", (function (_event) {
          return toggleModal(/* () */0);
        }));
  modalOverlayElement.addEventListener("click", (function (_event) {
          return toggleModal(/* () */0);
        }));
  formElement.addEventListener("submit", (function ($$event) {
          $$event.preventDefault();
          console.log(inputElement.value);
          return toggleModal(/* () */0);
        }));
  return /* () */0;
}

document.addEventListener("DOMContentLoaded", (function (param) {
        init(/* () */0);
        init$1(/* () */0);
        return /* () */0;
      }));

/*  Not a pure module */
