// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Core = require("@chakra-ui/core");
var BsChakra__Stack = require("@dck/bs-chakra-ui/src/BsChakra__Stack.bs.js");
var BsChakra__Heading = require("@dck/bs-chakra-ui/src/BsChakra__Heading.bs.js");

var hourRef = /* record */[/* contents */0];

var minutesRef = /* record */[/* contents */0];

function toTwoDigitString(number) {
  if (number < 10) {
    return "0" + number.toString();
  } else {
    return number.toString();
  }
}

function updateTime(setTime) {
  var today = new Date(Date.now());
  var hour = today.getHours();
  var minutes = today.getMinutes();
  if (hour !== hourRef[0] || minutes !== minutesRef[0]) {
    hourRef[0] = hour;
    minutesRef[0] = minutes;
    return Curry._1(setTime, (function (param) {
                  return /* tuple */[
                          toTwoDigitString(hour),
                          toTwoDigitString(minutes)
                        ];
                }));
  } else {
    return /* () */0;
  }
}

function Hour(Props) {
  var match = React.useState((function () {
          return /* tuple */[
                  "",
                  ""
                ];
        }));
  var setTime = match[1];
  var match$1 = match[0];
  React.useEffect((function () {
          updateTime(setTime);
          setInterval((function (param) {
                  updateTime(setTime);
                  return /* () */0;
                }), 1000);
          return undefined;
        }), ([]));
  return React.createElement(Core.Stack, Curry._3(BsChakra__Stack.makeProps(/* All */Block.__(0, [/* center */98248149]), /* All */Block.__(0, [/* center */98248149]), undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined)(true, undefined, React.createElement(Core.Heading, Curry._5(BsChakra__Heading.makeProps(/* All */Block.__(0, [/* xxxxxxl */-526015124]), undefined, undefined, undefined, undefined, /* white */-910341463)(null), undefined, /* h1 */23241, undefined, undefined, /* () */0), match$1[0], React.createElement("span", {
                              className: "blink"
                            }, ":"), match$1[1])), undefined, undefined, /* () */0));
}

var make = Hour;

exports.hourRef = hourRef;
exports.minutesRef = minutesRef;
exports.toTwoDigitString = toTwoDigitString;
exports.updateTime = updateTime;
exports.make = make;
/* react Not a pure module */
