// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Tenor$Ext = require("../resources/Tenor.bs.js");
var Belt_Array = require("bs-platform/lib/js/belt_Array.js");
var Belt_Option = require("bs-platform/lib/js/belt_Option.js");
var ReactUpdate = require("reason-react-update/src/ReactUpdate.bs.js");
var Core = require("@chakra-ui/core");
var BsChakra__Box$Ext = require("../vendor/chakra-ui/BsChakra__Box.bs.js");
var CopyToClipboard = require("copy-to-clipboard");
var BsChakra__Text$Ext = require("../vendor/chakra-ui/BsChakra__Text.bs.js");
var BsChakra__Image$Ext = require("../vendor/chakra-ui/BsChakra__Image.bs.js");
var BsChakra__Input$Ext = require("../vendor/chakra-ui/BsChakra__Input.bs.js");
var BsChakra__Stack$Ext = require("../vendor/chakra-ui/BsChakra__Stack.bs.js");
var BsChakra__Button$Ext = require("../vendor/chakra-ui/BsChakra__Button.bs.js");
var BsChakra__Spinner$Ext = require("../vendor/chakra-ui/BsChakra__Spinner.bs.js");
var BsChakra__IconButton$Ext = require("../vendor/chakra-ui/BsChakra__IconButton.bs.js");

function TenorWidget(Props) {
  var closeDrawer = Props.closeDrawer;
  var initialState = /* record */[
    /* keywords */"",
    /* results : NotAsked */0,
    /* resultLimit */5,
    /* loadingMore */false
  ];
  var match = ReactUpdate.useReducer(initialState, (function (action, state) {
          if (typeof action === "number") {
            switch (action) {
              case 0 : 
                  return /* SideEffects */Block.__(2, [(function (self) {
                                Tenor$Ext.search(self[/* state */1][/* keywords */0], self[/* state */1][/* resultLimit */2], /* () */0).then((function (data) {
                                          Curry._1(self[/* send */0], /* ReceiveSearchResults */Block.__(1, [/* Ok */Block.__(0, [data])]));
                                          return Promise.resolve(/* () */0);
                                        })).catch((function (err) {
                                        console.log(err);
                                        Curry._1(self[/* send */0], /* ReceiveSearchResults */Block.__(1, [/* Error */Block.__(1, [""])]));
                                        return Promise.resolve(/* () */0);
                                      }));
                                return undefined;
                              })]);
              case 1 : 
                  return /* UpdateWithSideEffects */Block.__(1, [
                            /* record */[
                              /* keywords */state[/* keywords */0],
                              /* results : Loading */1,
                              /* resultLimit */state[/* resultLimit */2],
                              /* loadingMore */state[/* loadingMore */3]
                            ],
                            (function (self) {
                                Curry._1(self[/* send */0], /* SearchGif */0);
                                return undefined;
                              })
                          ]);
              case 2 : 
                  return /* UpdateWithSideEffects */Block.__(1, [
                            /* record */[
                              /* keywords */state[/* keywords */0],
                              /* results */state[/* results */1],
                              /* resultLimit */state[/* resultLimit */2] + 5 | 0,
                              /* loadingMore */true
                            ],
                            (function (self) {
                                Curry._1(self[/* send */0], /* SearchGif */0);
                                return undefined;
                              })
                          ]);
              case 3 : 
                  return /* Update */Block.__(0, [initialState]);
              
            }
          } else {
            switch (action.tag | 0) {
              case 0 : 
                  return /* Update */Block.__(0, [/* record */[
                              /* keywords */action[0],
                              /* results */state[/* results */1],
                              /* resultLimit */state[/* resultLimit */2],
                              /* loadingMore */state[/* loadingMore */3]
                            ]]);
              case 1 : 
                  return /* Update */Block.__(0, [/* record */[
                              /* keywords */state[/* keywords */0],
                              /* results : Done */[action[0]],
                              /* resultLimit */state[/* resultLimit */2],
                              /* loadingMore */false
                            ]]);
              case 2 : 
                  var url = action[0];
                  return /* SideEffects */Block.__(2, [(function (param) {
                                CopyToClipboard(url);
                                Curry._1(closeDrawer, /* () */0);
                                return undefined;
                              })]);
              
            }
          }
        }));
  var dispatch = match[1];
  var state = match[0];
  var match$1 = state[/* keywords */0];
  var tmp = match$1 === "" ? null : React.createElement(Core.Box, Curry._5(BsChakra__Box$Ext.makeProps(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* All */Block.__(0, ["4px"]), undefined, undefined, /* All */Block.__(0, ["4px"]))(React.createElement(Core.IconButton, Curry._2(BsChakra__IconButton$Ext.makeProps(/* All */Block.__(0, [/* sm */25754]), undefined, undefined, undefined, /* Theme */Block.__(0, [/* close */-933029960]))(undefined, undefined, undefined, undefined, undefined, undefined, (function (param) {
                                return Curry._1(dispatch, /* CleanSearch */3);
                              })), undefined, /* () */0))), undefined, /* absolute */-1013592457, undefined, undefined, /* () */0));
  var match$2 = state[/* results */1];
  var tmp$1;
  if (typeof match$2 === "number") {
    tmp$1 = match$2 !== 0 ? React.createElement(Core.Spinner, BsChakra__Spinner$Ext.makeProps(/* blue500 */982465307, undefined)(undefined, undefined, undefined, /* md */24407, undefined, /* () */0)) : null;
  } else {
    var match$3 = match$2[0];
    tmp$1 = match$3.tag ? React.createElement(Core.Text, Curry._5(BsChakra__Text$Ext.makeProps(undefined, undefined, undefined, undefined, undefined, undefined)(match$3[0]), undefined, undefined, undefined, undefined, /* () */0)) : React.createElement(Core.Box, Curry._5(BsChakra__Box$Ext.makeProps(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined)(null), undefined, undefined, undefined, undefined, /* () */0), Belt_Array.map(match$3[0][/* results */1], (function (result) {
                  return Belt_Option.mapWithDefault(Belt_Array.get(result[/* media */2], 0), null, (function (medias) {
                                return React.createElement(Core.Box, Curry._5(BsChakra__Box$Ext.makeProps(undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* All */Block.__(0, [/* Theme */Block.__(0, [4])]), undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined)(React.createElement(Core.Button, Curry.app(BsChakra__Button$Ext.makeProps(undefined, undefined, undefined, /* All */Block.__(0, ["auto"]), /* All */Block.__(0, ["0px"]), /* All */Block.__(0, ["0px"]), undefined, /* All */Block.__(0, ["8px"]))(React.createElement(Core.Image, Curry._8(BsChakra__Image$Ext.makeProps(undefined, /* All */Block.__(0, ["300px"]), undefined)(medias[/* gif */0][/* url */0]), undefined, undefined, undefined, undefined, "4px", undefined, undefined, /* () */0))), [
                                                            /* outline */-507635838,
                                                            undefined,
                                                            undefined,
                                                            undefined,
                                                            undefined,
                                                            undefined,
                                                            undefined,
                                                            undefined,
                                                            (function (param) {
                                                                return Curry._1(dispatch, /* CopyGifUrlToClipboard */Block.__(2, [medias[/* gif */0][/* url */0]]));
                                                              }),
                                                            undefined,
                                                            undefined,
                                                            /* () */0
                                                          ]))), undefined, undefined, undefined, result[/* id */3], /* () */0));
                              }));
                })), React.createElement(Core.Button, Curry.app(BsChakra__Button$Ext.makeProps(undefined, undefined, /* All */Block.__(0, ["100%"]), undefined, undefined, undefined, undefined, undefined)("More"), [
                    /* ghost */324570959,
                    undefined,
                    undefined,
                    undefined,
                    state[/* loadingMore */3],
                    undefined,
                    undefined,
                    undefined,
                    (function (param) {
                        return Curry._1(dispatch, /* LoadMoreResults */2);
                      }),
                    undefined,
                    undefined,
                    /* () */0
                  ])));
  }
  return React.createElement(Core.DrawerContent, {
              children: null
            }, React.createElement(Core.DrawerCloseButton, { }), React.createElement(Core.DrawerHeader, {
                  children: "Search on Tenor",
                  borderBottomWidth: "1px"
                }), React.createElement(Core.DrawerBody, {
                  children: null,
                  overflowY: "scroll"
                }, React.createElement(Core.Stack, Curry._3(BsChakra__Stack$Ext.makeProps(undefined, undefined, undefined, undefined, /* All */Block.__(0, [/* Theme */Block.__(0, [4])]), undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined)(undefined, undefined, undefined, React.createElement("form", {
                                  onSubmit: (function (e) {
                                      e.preventDefault();
                                      return Curry._1(dispatch, /* SubmitSearch */1);
                                    })
                                }, React.createElement(Core.FormLabel, {
                                      children: "Keywords",
                                      htmlFor: "search"
                                    }), React.createElement(Core.Box, Curry._5(BsChakra__Box$Ext.makeProps(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined)(null), undefined, /* relative */903134412, undefined, undefined, /* () */0), React.createElement(Core.Input, Curry._4(BsChakra__Input$Ext.makeProps(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined)("omg, wtf, damn...", undefined, "search", undefined, undefined, (function ($$event) {
                                                    var value = $$event.target.value;
                                                    return Curry._1(dispatch, /* UpdateKeywords */Block.__(0, [value]));
                                                  }), undefined, undefined, state[/* keywords */0], undefined, undefined, undefined, undefined, undefined, undefined, undefined), undefined, /* text */-856044371, undefined, /* () */0)), tmp))), undefined, undefined, /* () */0)), tmp$1), React.createElement(Core.DrawerFooter, {
                  children: null,
                  borderTopWidth: "1px"
                }, React.createElement(Core.Button, Curry.app(BsChakra__Button$Ext.makeProps(undefined, undefined, undefined, undefined, undefined, undefined, /* All */Block.__(0, ["10px"]), undefined)("Cancel"), [
                          /* outline */-507635838,
                          undefined,
                          undefined,
                          undefined,
                          undefined,
                          undefined,
                          undefined,
                          undefined,
                          (function (param) {
                              return /* () */0;
                            }),
                          undefined,
                          undefined,
                          /* () */0
                        ])), React.createElement(Core.Button, Curry.app(BsChakra__Button$Ext.makeProps(undefined, /* blue */-1055309158, undefined, undefined, undefined, undefined, undefined, undefined)("Submit"), [
                          undefined,
                          undefined,
                          undefined,
                          undefined,
                          undefined,
                          undefined,
                          undefined,
                          undefined,
                          (function (param) {
                              return Curry._1(dispatch, /* SubmitSearch */1);
                            }),
                          undefined,
                          undefined,
                          /* () */0
                        ]))));
}

var make = TenorWidget;

exports.make = make;
/* react Not a pure module */
