// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Hour$Ext = require("./shared/Hour.bs.js");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var BsChakra__Box = require("@dck/bs-chakra-ui/src/BsChakra__Box.bs.js");
var BsChakra__Flex = require("@dck/bs-chakra-ui/src/BsChakra__Flex.bs.js");
var Core = require("@chakra-ui/core");
var FavoriteLinks$Ext = require("./shared/FavoriteLinks.bs.js");

function App$App(Props) {
  return React.createElement(Core.ThemeProvider, {
              theme: Core.theme,
              children: null
            }, React.createElement(Core.CSSReset, { }), React.createElement(Core.Flex, Curry._3(BsChakra__Flex.makeProps(undefined, undefined, /* All */Block.__(0, [/* Custom */Block.__(1, ["auto"])]), undefined, undefined, undefined, undefined, /* All */Block.__(0, [/* Theme */Block.__(0, [4])]), undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* All */Block.__(0, ["100%"]), undefined, /* All */Block.__(0, [/* center */98248149]), /* All */Block.__(0, [/* center */98248149]), undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined)(React.createElement(Core.Box, Curry._5(BsChakra__Box.makeProps(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined)(null), undefined, undefined, undefined, undefined, /* () */0), React.createElement(Hour$Ext.make, { }), React.createElement(FavoriteLinks$Ext.make, { }))), undefined, undefined, /* () */0)));
}

var App = /* module */[/* make */App$App];

ReactDOMRe.renderToElementWithId(React.createElement(App$App, { }), "root");

exports.App = App;
/*  Not a pure module */
