// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Hour$Ext = require("./shared/Hour.bs.js");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var Core = require("@chakra-ui/core");
var TenorWidget$Ext = require("./shared/TenorWidget.bs.js");
var BsChakra__Box$Ext = require("./vendor/chakra-ui/BsChakra__Box.bs.js");
var FavoriteLinks$Ext = require("./shared/FavoriteLinks.bs.js");
var BsChakra__Flex$Ext = require("./vendor/chakra-ui/BsChakra__Flex.bs.js");
var BsChakra__IconButton$Ext = require("./vendor/chakra-ui/BsChakra__IconButton.bs.js");

function App$App(Props) {
  var drawer = Core.useDisclosure();
  React.useEffect((function () {
          var onPress = function (e) {
            var match = e.keyCode;
            var match$1 = drawer.isOpen;
            if (match !== 71 || match$1) {
              return /* () */0;
            } else {
              return drawer.onOpen();
            }
          };
          window.addEventListener("keydown", onPress);
          return (function (param) {
                    window.addEventListener("keyword", onPress);
                    return /* () */0;
                  });
        }), /* array */[drawer.isOpen]);
  return React.createElement(Core.ThemeProvider, {
              theme: Core.theme,
              children: null
            }, React.createElement(Core.CSSReset, { }), React.createElement(Core.Flex, Curry._3(BsChakra__Flex$Ext.makeProps(undefined, undefined, /* All */Block.__(0, [/* Custom */Block.__(1, ["auto"])]), undefined, undefined, undefined, undefined, /* All */Block.__(0, [/* Theme */Block.__(0, [4])]), undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* All */Block.__(0, ["100%"]), undefined, /* All */Block.__(0, [/* center */98248149]), /* All */Block.__(0, [/* center */98248149]), undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined)(React.createElement(Core.Box, Curry._5(BsChakra__Box$Ext.makeProps(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined)(null), undefined, undefined, undefined, undefined, /* () */0), React.createElement(Hour$Ext.make, { }), React.createElement(FavoriteLinks$Ext.make, { }), React.createElement(Core.Box, Curry._5(BsChakra__Box$Ext.makeProps(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* All */Block.__(0, ["10px"]), undefined, undefined, /* All */Block.__(0, ["10px"]))(React.createElement(Core.IconButton, Curry._2(BsChakra__IconButton$Ext.makeProps(undefined, undefined, undefined, undefined, /* Theme */Block.__(0, [/* settings */188579043]))(/* ghost */324570959, undefined, undefined, undefined, undefined, undefined, (function (param) {
                                                        return drawer.onOpen();
                                                      })), undefined, /* () */0))), undefined, /* absolute */-1013592457, undefined, undefined, /* () */0)), React.createElement(Core.Drawer, {
                                  children: null,
                                  isOpen: drawer.isOpen,
                                  placement: "right",
                                  onClose: (function (param) {
                                      return drawer.onClose();
                                    })
                                }, React.createElement(Core.DrawerOverlay, { }), React.createElement(TenorWidget$Ext.make, {
                                      closeDrawer: (function (param) {
                                          return drawer.onClose();
                                        })
                                    })))), undefined, undefined, /* () */0)));
}

var App = /* module */[/* make */App$App];

ReactDOMRe.renderToElementWithId(React.createElement(App$App, { }), "root");

exports.App = App;
/*  Not a pure module */
